### PR TITLE
Add Number, Radio and Dropdown setting types

### PR DESCRIPTION
**Pull request by samfun123**
demo

### CODE REVIEW

**Comment by Jiiks** [comment]
Can you style them to be like Discord settings? I can do it later as well if not.

Radio:
image

Dropdown:
image

**Comment by samfun123** [comment]
I can see the difference for the Radio buttons, but what do you want me to change about the Dropdown menu?

**Comment by Jiiks** [comment]
Colours unless it's just the gif messing them up..? and the arrow should flipy when open.

**Comment by rauenzi** [comment]
Also for the dropdown it should be wider than the longest option so it doesnt change size when the selection changes, like in the screenshot Jiiks showed where it is significantly larger

**Pull request merged**
